<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSPDFSlot extends BasepkContextCMSPDFSlot
{
  public function refreshSlot()
  {
    return pkContextCMSImageSlot::refreshImageSlot($this);
  }
}