<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSImageSlot extends BasepkContextCMSImageSlot
{
  public function isOutlineEditable()
  {
    return false;
  }
}
