options:
  type: INNODB

pkContextCMSImageSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSImage'

pkContextCMSButtonSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSButton'

pkContextCMSSlideshowSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSSlideshow'

pkContextCMSVideoSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSVideo'

pkContextCMSMediaBrowserSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSMediaBrowser'

pkContextCMSPDFSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSPDF'
