options:
  type: INNODB

pkContextCMSImageSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSImage'

pkContextCMSSlideshowSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSSlideshow'

pkContextCMSVideoSlot:
  inheritance:
    extends: pkContextCMSSlot
    type: column_aggregation
    keyField: type
    keyValue: 'pkContextCMSVideo'
